#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-readODS
Version  : 2.1.0
Release  : 35
URL      : https://cran.r-project.org/src/contrib/readODS_2.1.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/readODS_2.1.0.tar.gz
Summary  : Read and Write ODS Files
Group    : Development/Tools
License  : GPL-3.0
Requires: R-readODS-lib = %{version}-%{release}
Requires: R-cellranger
Requires: R-cpp11
Requires: R-readr
Requires: R-stringi
Requires: R-tibble
Requires: R-vctrs
Requires: R-zip
BuildRequires : R-cellranger
BuildRequires : R-cpp11
BuildRequires : R-readr
BuildRequires : R-stringi
BuildRequires : R-tibble
BuildRequires : R-vctrs
BuildRequires : R-zip
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# readODS <img src="man/figures/read_ods_logo.png"  align="right" height="200" />

%package lib
Summary: lib components for the R-readODS package.
Group: Libraries

%description lib
lib components for the R-readODS package.


%prep
%setup -q -n readODS
pushd ..
cp -a readODS buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694450740

%install
export SOURCE_DATE_EPOCH=1694450740
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/readODS/DESCRIPTION
/usr/lib64/R/library/readODS/INDEX
/usr/lib64/R/library/readODS/Meta/Rd.rds
/usr/lib64/R/library/readODS/Meta/features.rds
/usr/lib64/R/library/readODS/Meta/hsearch.rds
/usr/lib64/R/library/readODS/Meta/links.rds
/usr/lib64/R/library/readODS/Meta/nsInfo.rds
/usr/lib64/R/library/readODS/Meta/package.rds
/usr/lib64/R/library/readODS/Meta/vignette.rds
/usr/lib64/R/library/readODS/NAMESPACE
/usr/lib64/R/library/readODS/NEWS.md
/usr/lib64/R/library/readODS/R/readODS
/usr/lib64/R/library/readODS/R/readODS.rdb
/usr/lib64/R/library/readODS/R/readODS.rdx
/usr/lib64/R/library/readODS/R/sysdata.rdb
/usr/lib64/R/library/readODS/R/sysdata.rdx
/usr/lib64/R/library/readODS/WORDLIST
/usr/lib64/R/library/readODS/doc/index.html
/usr/lib64/R/library/readODS/doc/overview.R
/usr/lib64/R/library/readODS/doc/overview.Rmd
/usr/lib64/R/library/readODS/doc/overview.html
/usr/lib64/R/library/readODS/help/AnIndex
/usr/lib64/R/library/readODS/help/aliases.rds
/usr/lib64/R/library/readODS/help/figures/read_ods_logo.png
/usr/lib64/R/library/readODS/help/paths.rds
/usr/lib64/R/library/readODS/help/readODS.rdb
/usr/lib64/R/library/readODS/help/readODS.rdx
/usr/lib64/R/library/readODS/html/00Index.html
/usr/lib64/R/library/readODS/html/R.css
/usr/lib64/R/library/readODS/template/META-INF/manifest.xml
/usr/lib64/R/library/readODS/template/content.xml
/usr/lib64/R/library/readODS/template/meta.xml
/usr/lib64/R/library/readODS/template/mimetype
/usr/lib64/R/library/readODS/template/styles.xml
/usr/lib64/R/library/readODS/tests/spelling.R
/usr/lib64/R/library/readODS/tests/testdata/1996-2000.ods
/usr/lib64/R/library/readODS/tests/testdata/cellranger_issue57.ods
/usr/lib64/R/library/readODS/tests/testdata/col_types.ods
/usr/lib64/R/library/readODS/tests/testdata/datasets.ods
/usr/lib64/R/library/readODS/tests/testdata/decimal_comma.ods
/usr/lib64/R/library/readODS/tests/testdata/eating_spaces.ods
/usr/lib64/R/library/readODS/tests/testdata/empty.fods
/usr/lib64/R/library/readODS/tests/testdata/empty.ods
/usr/lib64/R/library/readODS/tests/testdata/excel_repeat.ods
/usr/lib64/R/library/readODS/tests/testdata/flat.fods
/usr/lib64/R/library/readODS/tests/testdata/flights_head.RDS
/usr/lib64/R/library/readODS/tests/testdata/fuzz.txt
/usr/lib64/R/library/readODS/tests/testdata/horrible.ods
/usr/lib64/R/library/readODS/tests/testdata/issue81.ods
/usr/lib64/R/library/readODS/tests/testdata/layout_test.ods
/usr/lib64/R/library/readODS/tests/testdata/layout_test.xls
/usr/lib64/R/library/readODS/tests/testdata/layout_test.xlsx
/usr/lib64/R/library/readODS/tests/testdata/legend.rds
/usr/lib64/R/library/readODS/tests/testdata/linkeddata.ods
/usr/lib64/R/library/readODS/tests/testdata/lotsofnothing_test.ods
/usr/lib64/R/library/readODS/tests/testdata/merged.ods
/usr/lib64/R/library/readODS/tests/testdata/mergerandgreaterthanlibreoffice.ods
/usr/lib64/R/library/readODS/tests/testdata/multiline_cells.ods
/usr/lib64/R/library/readODS/tests/testdata/multisheet.ods
/usr/lib64/R/library/readODS/tests/testdata/na_test.ods
/usr/lib64/R/library/readODS/tests/testdata/na_test2.ods
/usr/lib64/R/library/readODS/tests/testdata/na_test3.ods
/usr/lib64/R/library/readODS/tests/testdata/nocells.fods
/usr/lib64/R/library/readODS/tests/testdata/norows.fods
/usr/lib64/R/library/readODS/tests/testdata/onerow.ods
/usr/lib64/R/library/readODS/tests/testdata/perform.ods
/usr/lib64/R/library/readODS/tests/testdata/readODStestfilegoogledocscreated.ods
/usr/lib64/R/library/readODS/tests/testdata/rep_check.ods
/usr/lib64/R/library/readODS/tests/testdata/repeat_rows.ods
/usr/lib64/R/library/readODS/tests/testdata/reprow.ods
/usr/lib64/R/library/readODS/tests/testdata/smartSheetTest.ods
/usr/lib64/R/library/readODS/tests/testdata/starwars.ods
/usr/lib64/R/library/readODS/tests/testdata/starwars10.rds
/usr/lib64/R/library/readODS/tests/testdata/sum.ods
/usr/lib64/R/library/readODS/tests/testdata/table.ods
/usr/lib64/R/library/readODS/tests/testdata/test.ods
/usr/lib64/R/library/readODS/tests/testdata/test_naming.ods
/usr/lib64/R/library/readODS/tests/testdata/wild_character_encoding.ods
/usr/lib64/R/library/readODS/tests/testthat.R
/usr/lib64/R/library/readODS/tests/testthat/plant.ods
/usr/lib64/R/library/readODS/tests/testthat/test_as_tibble.R
/usr/lib64/R/library/readODS/tests/testthat/test_cellranger.R
/usr/lib64/R/library/readODS/tests/testthat/test_col_types.R
/usr/lib64/R/library/readODS/tests/testthat/test_issue81.R
/usr/lib64/R/library/readODS/tests/testthat/test_legacy.R
/usr/lib64/R/library/readODS/tests/testthat/test_list_sheets.R
/usr/lib64/R/library/readODS/tests/testthat/test_merged.R
/usr/lib64/R/library/readODS/tests/testthat/test_multiline.R
/usr/lib64/R/library/readODS/tests/testthat/test_na.R
/usr/lib64/R/library/readODS/tests/testthat/test_read_fods.R
/usr/lib64/R/library/readODS/tests/testthat/test_read_ods.R
/usr/lib64/R/library/readODS/tests/testthat/test_verbose.R
/usr/lib64/R/library/readODS/tests/testthat/test_write_ods.R
/usr/lib64/R/library/readODS/tests/testthat/test_write_ods_append_update.R
/usr/lib64/R/library/readODS/tests/testthat/test_write_sheet.R
/usr/lib64/R/library/readODS/tests/testthat/test_xml_fuzz.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/readODS/libs/readODS.so
/usr/lib64/R/library/readODS/libs/readODS.so.avx2
/usr/lib64/R/library/readODS/libs/readODS.so.avx512
